{% set version = datetime.datetime.utcnow().strftime('%Y.%m.%d.%H.%M.%S') %}

package:
  name: conda-forge-pinning
  version: {{ version }}

source:
  path: .

build:
  number: 0
  noarch: generic
  script:
    - cp conda_build_config.yaml $PREFIX                              # [unix]
    - mkdir -p $PREFIX/share/conda-forge/migrations                   # [unix]
    - cp migrations/*.yaml $PREFIX/share/conda-forge/migrations/      # [unix]
    - cp migrations/*.exyaml $PREFIX/share/conda-forge/migrations/    # [unix]
    - mkdir -p $PREFIX/share/conda-forge/migration_support            # [unix]
    - cp migration_support/* $PREFIX/share/conda-forge/migration_support/   # [unix]
    - echo "This package can't be built on windows"                   # [win]
    - exit 1                                                          # [win]

test:
  files:
    - test_migrations.py
  requires:
    - python >=3.8
    - pyyaml
    - pytest
    - git
  commands:
    - test -f $PREFIX/conda_build_config.yaml                         # [unix]
    - test -f $PREFIX/share/conda-forge/migrations/example.exyaml     # [unix]
    - test -d $PREFIX/share/conda-forge/migration_support             # [unix]
    - export GIT_REPO_LOC={{ os.environ.get("FEEDSTOCK_ROOT", "") }}  # [unix]
{% if not version.startswith("2025.12.15") %}
    - pytest -vvs test_migrations.py                                  # [unix]
{% endif %}

about:
  summary: The baseline versions of software for the conda-forge ecosystem
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  home: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-pinning

extra:
  recipe-maintainers:
    - conda-forge/Core
