{% set version = "2018.05.07" %}

package:
  name: conda-forge-pinning
  version: {{ version }}

source:
  path: .

build:
  number: 0
  noarch: generic
  script:
    - cp conda_build_config.yaml $PREFIX      # [unix]
    - copy conda_build_config.yaml %PREFIX%   # [win]

test:
  commands:
    - test -f $PREFIX/conda_build_config.yaml

about:
  summary: The baseline versions of software for the conda-forge ecosystem
  license: BSD 3-Clause
  license_family: BSD
  home: https://conda-forge.org/docs/meta.html#pinning-packages

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
